import { Language, SensorItem, EmergencyService } from './types';

export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    welcome: "Welcome to Gadi Dost",
    login_subtitle: "Your trusted partner on the road",
    email: "Email Address",
    password: "Password",
    sign_in: "Sign In",
    sign_up: "Sign Up",
    no_account: "Don't have an account?",
    have_account: "Already have an account?",
    create_account: "Create Account",
    forgot_password: "Forgot Password?",
    login_as: "Login as",
    driver: "Driver",
    fleet_owner: "Fleet Owner",
    transporter: "Transporter",
    customer: "Customer",
    dashboard: "Dashboard",
    gps_marketplace: "GPS Marketplace",
    emergency: "Emergency",
    bilty_book: "Bilty Book",
    truck_booking: "Truck Booking",
    load_calculator: "Load Calculator",
    logout: "Logout",
    gps_install: "Install GPS",
    gps_request: "Request GPS",
    gps_premium: "Buy Premium",
    sensors: "Sensors",
    emergency_help: "Emergency Request",
    tow_truck: "Tow Truck",
    mechanic: "Mechanic",
    fuel_delivery: "Fuel Delivery",
    puncture: "Tire / Puncture",
    battery: "Battery Jump",
    calculating: "Calculating...",
    estimate: "Get Estimate",
    material: "Material Type",
    weight: "Weight (kg/tons)",
    distance: "Distance (km)",
    pickup: "Pickup Location",
    drop: "Drop Location",
    find_trucks: "Find Trucks",
    book_now: "Book Now",
    loading: "Loading...",
    bilty_url: "Bilty Website URL",
    go_to_bilty: "Go to Bilty Portal",
    upload_pod: "Upload POD",
    language: "Language / भाषा",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    home: "Home",
    admin: "Admin",
    role: "Role",
    buy: "Buy",
    schedule: "Schedule",
  },
  [Language.HINDI]: {
    welcome: "गाड़ी दोस्त में आपका स्वागत है",
    login_subtitle: "सड़क पर आपका भरोसेमंद साथी",
    email: "ईमेल पता",
    password: "पासवर्ड",
    sign_in: "साइन इन करें",
    sign_up: "साइन अप करें",
    no_account: "खाता नहीं है?",
    have_account: "क्या आपके पास पहले से एक खाता मौजूद है?",
    create_account: "खाता बनाएं",
    forgot_password: "पासवर्ड भूल गए?",
    login_as: "लॉगिन करें",
    driver: "ड्राइवर",
    fleet_owner: "फ्लीट मालिक",
    transporter: "ट्रांसपोर्टर",
    customer: "ग्राहक",
    dashboard: "डैशबोर्ड",
    gps_marketplace: "जीपीएस मार्केट",
    emergency: "आपातकालीन",
    bilty_book: "बिल्टी बुक",
    truck_booking: "ट्रक बुकिंग",
    load_calculator: "लोड कैलकुलेटर",
    logout: "लॉग आउट",
    gps_install: "जीपीएस लगवाएं",
    gps_request: "जीपीएस अनुरोध",
    gps_premium: "प्रीमियम खरीदें",
    sensors: "सेंसर",
    emergency_help: "मदद मांगें",
    tow_truck: "टो ट्रक",
    mechanic: "मैकेनिक",
    fuel_delivery: "ईंधन वितरण",
    puncture: "टायर / पंचर",
    battery: "बैटरी जंप",
    calculating: "गणना हो रही है...",
    estimate: "अनुमान प्राप्त करें",
    material: "सामग्री का प्रकार",
    weight: "वजन (किग्रा/टन)",
    distance: "दूरी (किमी)",
    pickup: "पिकअप स्थान",
    drop: "ड्रॉप स्थान",
    find_trucks: "ट्रक खोजें",
    book_now: "बुक करें",
    loading: "लोड हो रहा है...",
    bilty_url: "बिल्टी वेबसाइट URL",
    go_to_bilty: "बिल्टी पोर्टल पर जाएं",
    upload_pod: "POD अपलोड करें",
    language: "भाषा / Language",
    dark_mode: "डार्क मोड",
    light_mode: "लाइट मोड",
    home: "होम",
    admin: "एडमिन",
    role: "भूमिका",
    buy: "खरीदें",
    schedule: "शेड्यूल करें",
  }
};

export const SENSORS: SensorItem[] = [
  { id: '1', name: 'Fuel Sensor', price: 2500, description: 'Monitor fuel levels and theft.', icon: 'fuel' },
  { id: '2', name: 'Door Sensor', price: 1200, description: 'Alerts when container doors open.', icon: 'door' },
  { id: '3', name: 'Temp Sensor', price: 3000, description: 'For reefer trucks/cold chain.', icon: 'thermometer' },
  { id: '4', name: 'Blink Sensor', price: 800, description: 'Indicator usage monitoring.', icon: 'lightbulb' },
];

export const EMERGENCY_SERVICES: EmergencyService[] = [
  { id: 'tow', name: 'Tow Truck', icon: 'truck', eta: '25 mins' },
  { id: 'mechanic', name: 'Mechanic', icon: 'wrench', eta: '15 mins' },
  { id: 'fuel', name: 'Fuel', icon: 'droplet', eta: '20 mins' },
  { id: 'tire', name: 'Tire/Puncture', icon: 'disc', eta: '30 mins' },
  { id: 'medical', name: 'Medical', icon: 'heart', eta: '10 mins' },
  { id: 'police', name: 'Police', icon: 'shield', eta: '15 mins' },
];